### PR TITLE
Feature/diskspace check

### PR DESCRIPTION
**Pull request by sdressler**

### CODE REVIEW

**Comment by jukoson** [comment]
Can you think of a way to figure out the actual path of PGDATA on the host from the running docker container ?

**Comment by sdressler** [comment]
> Can you think of a way to figure out the actual path of PGDATA on the host from the running docker container ? With that we could have this check always enabled without the need to specify the directory

That would certainly work, but then the whole solution only works when using our stuff and not e.g. on AWS, I believe.

**Comment by jukoson** [comment]
> > Can you think of a way to figure out the actual path of PGDATA on the host from the running docker container ? With that we could have this check always enabled without the need to specify the directory
> 
> That would certainly work, but then the whole solution only works when using our stuff and not e.g. on AWS, I believe.

A dirty option is to check whether an s64da container is running, and then checking the container volumes or PGDATA directly. We could turn the check into a huge warning anyways, not failing unconditionally.

**Comment by sdressler** [comment]
Stupid question: why not have it explicit like implemented?

**Pull request merged**
